### ISSUE TITLE
US03 - Eu, como cuidador, quero alterar as informações do meu perfil para manter meus dados atualizados

### ISSUE THREAD

**Issue by Faehzin** [fga-eps-mds/2024-2-GEROcuidado-Docs#100]
**Tarefas**

- [x]  Validar o funcionamento do botão "Editar Perfil".
- [x]  Testar campos de edição (data de nascimento, senha, características gerais e foto de perfil).
- [x]  Garantir que as alterações são salvas corretamente.
- [x]  Verificar se há uma mensagem de confirmação após salvar as alterações.

**Critérios de Aceitação**
_Cenários de Teste:_

* Acessar a Edição do Perfil:

- [x] O botão "Editar Perfil" deve estar disponível na tela de perfil.
- [x] Ao clicar, o usuário deve ser levado a uma tela com os campos editáveis.

* Alteração de Dados:

- [x] Os campos Data de Nascimento, Senha, Características Gerais e Foto de Perfil devem permitir edição.
- [x] Para a senha, deve haver validação de força e confirmação de senha.
- [x] A foto de perfil deve ser alterada por meio de upload.

* Salvar Alterações:

- [x] Após clicar em "Salvar", os dados atualizados devem ser exibidos corretamente no perfil.
- [x] Mensagem de sucesso: "Informações atualizadas com sucesso."

* Erro de Validação:

- [x] Caso algum campo obrigatório não seja preenchido corretamente, exibir mensagem de erro.

**Comment by viniciused26** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MDS-EPS-GEROCuidado2024-2-6723bd5d785f79001724a26e/issues/fga-eps-mds/2024-2-GEROcuidado-Docs/100?planning-poker) with Zenhub @Afrontoso @ArturVinicius @Faehzin @jvopBR @Kauan-F20 @LeoFacB @Matheus-0217
