### ISSUE TITLE
US04 - Eu, como cuidador, quero denunciar um post ofensivo, e por o motivo da denuncia

### ISSUE THREAD

**Issue by Faehzin** [fga-eps-mds/2024-2-GEROcuidado-Docs#101]
**Tarefas**

- [x]  Validar a visibilidade do botão "Denunciar" em cada post.
- [x]  Criar o formulário de denúncia, incluindo o campo para selecionar ou escrever o motivo (seleção de motivos ou caixa de texto para escrever o motivo?)
- [ ]  Garantir que a denúncia seja enviada com sucesso para o sistema de moderação -- m usuário moderador.
- [x]  Confirmar a exibição de uma mensagem de sucesso ao usuário após a denúncia.

**Critérios de Aceitação**
_Cenários de Teste:_

Acessar a Opção de Denúncia:

- [x] O botão "Denunciar" deve estar visível em cada post.
- [x] Ao clicar, o usuário deve ser redirecionado para um formulário de denúncia.

**para Preencher a Denúncia, o formulário deve incluir:**

- [ ] Motivo da denúncia: Seleção em lista (ex.: conteúdo impróprio, spam, assédio, etc.) ou um campo de texto para detalhes.
- [x] Todos os campos obrigatórios devem ser preenchidos.

**Enviar a Denúncia:**

- [ ] Após clicar em "Enviar Denúncia", a denúncia deve ser registrada no sistema de moderação, para conseguir 
- [x] Mensagem de sucesso: "Sua denúncia foi enviada e será analisada em breve."

**Erro no Envio:**

- [ ] Caso haja problemas no envio, quero que apareça uma mensagem "Ocorreu um erro ao enviar a denúncia. Tente novamente mais tarde." ou similar

Protótipo: https://www.figma.com/proto/sls2BQgP3eNQsK7p9Ik0dF/Gero-Cuidado-2024.2?node-id=1-2084&t=gSezWv2PnJ35fSh5-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1

**Comment by Faehzin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MDS-EPS-GEROCuidado2024-2-6723bd5d785f79001724a26e/issues/fga-eps-mds/2024-2-GEROcuidado-Docs/101?planning-poker) with Zenhub @Afrontoso @jvopBR @Kauan-F20 @LeoFacB @Matheus-0217 @viniciused26
