### ISSUE TITLE
Eu como usuário administrador quero poder Cadastrar, ler, editar e excluir conta de cuidador com fins de gerenciamento

### ISSUE THREAD

**Issue by F1reFinger** [fga-eps-mds/2024-2-GEROcuidado-Docs#44]
## **Tarefas**

- [ ] Verificar a funcionalidade de cadastro de cuidadores.
- [ ] Verificar a funcionalidade de leitura de contas de cuidadores.
- [ ] Verificar a funcionalidade de edição de contas de cuidadores.
- [ ] Verificar a funcionalidade de exclusão de contas de cuidadores

## **Critérios de Aceitação**

- [ ] Cadastro de cuidador.
- [ ] Leitura de dados de cuidador.
- [ ]  Edição de dados de cuidador.
- [ ]  Exclusão de cuidador.

## **Cenários de Teste**

- [ ] **Cadastro de cuidador**: Verificar se ao cadastrar um novo cuidador, os dados são salvos corretamente e aparecem no sistema.
- [ ] **Leitura de dados de cuidador**: Garantir que o administrador consiga visualizar todas as informações cadastradas de um cuidador.
- [ ] **Edição de dados de cuidador**: Confirmar que o administrador pode editar as informações de um cuidador, como nome, e-mail ou telefone.
- [ ] **Exclusão de cuidador**: Validar que ao excluir um cuidador, a conta é removida completamente do sistema.

**Comment by Matheus-0217** [comment]
on producer!!
