### ISSUE TITLE
Eu como usuário quero poder Acessar a plataforma com uma conta para que eu possa acompanhar meu cadasto

### ISSUE THREAD

**Issue by F1reFinger** [fga-eps-mds/2024-2-GEROcuidado-Docs#45]
**Tarefas**

- [ ] - Permitir que o usuário anote tarefas em um bloco de notas.
- [ ] - Implementar envio de notificações push no aplicativo.
- [ ] - Permitir que o usuário visualize, edite ou exclua lembretes configurados.
- [ ] - Testar notificações em diferentes dispositivos para garantir a entrega.
- [x] - Testar

**Critérios de Aceitação**

- [ ] - O usuário deve conseguir acessar a seção de "Tarefas" no aplicativo para cadastrar novas tarefas diárias.
- [ ]  - O usuário deve conseguir configurar um horário para cada tarefa, incluindo uma descrição opcional.
- [ ]  - O aplicativo deve enviar notificações push no horário configurado.
- [ ]  - O usuário deve conseguir visualizar todas as notificações pendentes na "agenda" do aplicativo.
- [ ]  - As notificações devem ser intuitivas, exibindo o nome da tarefa e um botão para abrir.
- [ ]  - O sistema deve permitir reprogramar tarefas.

**Protótipo**

https://www.figma.com/proto/EiPhCTq1UZrZRp45lBIhnE/Untitled?node-id=1-11&t=13sXojm6d10GI4Or-1
