### ISSUE TITLE
Como cuidador, quero me cadastrar no aplicativo para conseguir armazenar minhas informações necessárias

### ISSUE THREAD

**Issue by Faehzin** [fga-eps-mds/2024-2-GEROcuidado-Docs#70]
**Tarefas**

- [ ]  Criar a funcionalidade de cadastro de cuidadores.
- [ ]  Permitir que o cuidador insira informações básicas como nome, e-mail, telefone, e senha.
- [ ]  Implementar validação de dados (ex.: e-mail válido, senha com critérios mínimos de segurança).
- [ ]  Criar uma interface para o cuidador visualizar e atualizar suas informações pessoais após o cadastro.

**Critérios de Aceitação**

- [ ]  O aplicativo deve oferecer uma seção de cadastro na tela inicial com campos obrigatórios para:

> -  Nome completo
> - E-mail
> - Telefone
> - Senha (mínimo de 8 caracteres, contendo letras e números)

**Comment by viniciused26** [comment]
Esse épico precisou ser reescrito e por isso foi fechado.
