### ISSUE TITLE
US02 - Eu, como cuidador, quero criar um novo evento na agenda do idoso, para organizar suas atividade

### ISSUE THREAD

**Issue by Faehzin** [fga-eps-mds/2024-2-GEROcuidado-Docs#98]
**Tarefas**
 

- [x] Configurar para o botão "Adicionar Evento" estar visível na tela de agenda.
- [x]  Validar e criar o formulário de criação de evento (título, data, hora e descrição).
- [x]  Testar a exibição do evento criado na agenda.
- [x]  Programar mensagem de sucesso.
- [x]  Definir diferentes cores apra eventos (dourado, ou a própria cor do GERO)

**Critérios de Aceitação**
_Cenários de Teste:_

* Botão de Criação de Evento:

- [x] O botão "Adicionar Evento" deve estar disponível na tela de agenda.

* Formulário de Novo Evento:

Ao clicar no botão, o usuário deve ser redirecionado para um formulário com os seguintes campos:

- [x] Título do Evento
- [x] Data
- [x] Hora
- [x] Descrição

Todos os campos obrigatórios devem ser validados antes de salvar.

_Exibição do Evento:_

- [x] Após salvar, o evento deve aparecer na agenda com as informações fornecidas.
- [x] Mensagem de sucesso: "Evento adicionado com sucesso."

**PROTÓTIPO**

link: https://www.figma.com/proto/EiPhCTq1UZrZRp45lBIhnE/GERO-CUIDADO?node-id=49-1551&node-type=canvas&t=rYAhYkeib1w4Ww6z-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1
